name: Daily Knowledge Hub Pipeline

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 03:00 UTC
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      MEDIUM_RSS_URL: ${{ secrets.MEDIUM_RSS_URL }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Medium Processing Pipeline
        run: |
          python processing/run_pipeline.py ingest
          echo "✅ Medium ingestion completed"

      - name: Run Data Aggregation
        run: |
          python processing/run_pipeline.py aggregate
          echo "✅ Data aggregation completed"

      - name: Run AI Processing
        run: |
          python processing/run_pipeline.py ai
          echo "✅ AI processing completed"
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Commit and Push Results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/ sources/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily knowledge update: $(date -u +%Y-%m-%d)"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Pipeline Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daily-knowledge-${{ github.run_number }}
          path: |
            data/
            sources/
          retention-days: 7

      - name: Error Handling and Notification
        if: failure()
        run: |
          echo "Pipeline failed! Check logs for details."
          # Add notification logic here if needed 